### ISSUE TITLE
bug: Reset password link for cloud does not work

### ISSUE THREAD

**Issue by danielkuske** [langfuse/langfuse#4614] opened 2024-12-06 14:33 UTC
### Describe the bug

I tried to reset my password and received the e-mail, as expected. When I click on the button in the mail I end up on a page showing me this error:
<img width="266" alt="Screenshot 2024-12-06 at 15 27 31" src="https://github.com/user-attachments/assets/6943183c-2aa1-408c-9a96-0516a336afd9">

### To reproduce

Try to reset the password via ["forgot password"](https://cloud.langfuse.com/auth/reset-password)

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment] 2024-12-09 12:41
Thanks for sharing. I cannot reproduce this issue; I just successfully reset my password. 

Could you please share the URL of the error page?

**Comment by marcklingen** [comment] 2024-12-12 00:08
can you confirm that this is still an ongoing issue? I still cannot reproduce this unfortunately

**Comment by danielkuske** [comment] 2024-12-12 11:12
Hi Marck,

the issue still occurs for me. Here is the link that I got via email:
https://cloud.langfuse.com/api/auth/callback/email?callbackUrI=https%3A%2F%2Fcloud.langfuse.com%2Fauth%2Freset-password&token=<the-token>&email=daniel.kuske%40statista.com

and the URL of the error page is this:
https://cloud.langfuse.com/auth/error?error=Verification

Thanks for your help!

**Comment by marcklingen** [comment] 2024-12-13 02:12
Reached out via the chat, thanks for the ping and sorry for the slow response here

**Comment by marcklingen** [comment] 2024-12-13 02:13
Let's have a quick call to resolve this once and for all (shared my calendar)

**Comment by marcklingen** [comment] 2024-12-13 15:15
Thanks for your time. For this ticket: it seems like subsequent passwort reset attempts do not always work. I will investigate this.

**Comment by marcklingen** [comment] 2024-12-20 21:58
> it seems like subsequent passwort reset attempts do not always work. I will investigate this.

False assumption, works as expected and I cannot reproduce this. Closing this issue, let's reopen if this happens again

**Closed by marcklingen** 2024-12-20 21:58 UTC
Labels: bug
