### ISSUE TITLE
feat(auth): add GitLab auth provider

### ISSUE THREAD

**Issue by jsirex** [langfuse/langfuse#2468] opened 2024-06-27 15:45 UTC
> **EDIT** (@marcklingen): GitLab auth can be added to Langfuse via the GitLab auth [provider](https://next-auth.js.org/providers/gitlab) in nextauth. Let's keep this issue open to track the implementation of this provider. Happy to help you contribute this.

### Describe the bug

I tried to integration langfuse with gitlab via application oauth.
And it seemed for me that oauth process itself was ok, but at the very end step it failed with:
```
 prisma:error 
 Invalid `prisma.account.create()` invocation:
 
 {
   data: {
     provider: "custom",
     type: "oauth",
     providerAccountId: "21949",
     access_token: "AAAAAAAAAAAAAAAAAAAAA",
     token_type: "Bearer",
     expires_at: 1719504313,
     refresh_token: "RRRRRRRRRRRRRRRRRRRRRR",
     scope: "openid email profile",
     created_at: 1719497112,
     ~~~~~~~~~~
     id_token: "xxxxxxxxxxxxxxx.yyyyyyyyyyyyyyyyyyyy.zzzzzzzzzzzzzzzzzz-qqqqqqqqqqqqqqq-wwwwwwwwwwwwwwww-eeeeeee-rrrrrrrrr-tttttttttttttt",
     userId: "HHHHHHHHHHHHH",
 ?   id?: String,
 ?   expires_in?: Int | Null,
 ?   ext_expires_in?: Int | Null,
 ?   session_state?: String | Null
   }
 }
 
 Unknown argument `created_at`. Available options are marked with ?.
 [next-auth][error][adapter_error_linkAccount] 
 https://next-auth.js.org/errors#adapter_error_linkaccount 
 Invalid `prisma.account.create()` invocation:
 

```

### To reproduce

1. Create an oauth application at gitlab instance
2. Run latest langfuse with AUTH_CUSTOM_* variables as described in docs
3. Try to sign in

ENVS:
```
...
AUTH_CUSTOM_CLIENT_ID=XXXXXXXXXXXXXXXXX
AUTH_CUSTOM_CLIENT_SECRET=YYYYYYYYYYYYYYYYYYYYY
AUTH_CUSTOM_ISSUER=https://gitlab.company.com
AUTH_CUSTOM_NAME=gitlab
AUTH_CUSTOM_ALLOW_ACCOUNT_LINKING=true
....
```

### SDK and container versions

container version: 2.57.0

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment] 2024-06-27 16:47
if you need gitlab auth, please contribute support for gitlab as it is natively supported by NextAuth

**Comment by marcklingen** [comment] 2024-06-27 16:50
GitLab auth should be added via the native GitLab auth provider of nextauth. I've edited the issue accordingly.

Let me know in case you are interested to contribute this auth provider, happy to help

**Comment by jsirex** [comment] 2024-06-28 10:36
I don't get it. What purpose of custom OAuth provider then? Isn't it for oauth not supported yet?
GitLab is not supported, so I tried custom one.
But, it seemed for me that bug is not related to OAuth itself, but to a missing field "created_at" in DB.

**Comment by marcklingen** [comment] 2024-06-28 12:36
Sorry for the bad wording above, totally agree that this should work via the custom provider, I just wanted to add that a dedicated GitLab Provider would be nice as well for better DX.

I've had a look a this issue, nextauth removed `created_at` in v4, I am unsure why this is an issue here: https://next-auth.js.org/getting-started/upgrade-v4#schema-changes

We could add the created_at column which does not have negative side-effects to resolve this. Do you have an alternative suggestion?

**Comment by jsirex** [comment] 2024-06-28 17:12
[HTTP 418 :)](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418)

In other words I know nothing about next-auth, so no ideas

**Comment by vanshavenger** [comment] 2024-10-05 07:33
@marcklingen we can close this now right?

**Comment by marcklingen** [comment] 2024-10-08 00:19
yes, thanks for following up on it. I assumed that the issue is automatically closed/linked via the PR. Thanks again for your contribution on this!

**Closed by marcklingen** 2024-10-08 00:19 UTC
Labels: good first issue, feat-auth, self-hosting, hacktoberfest
