### ISSUE TITLE
bug: Usage and Cost Calculation Issue for GPT-4 Model

### ISSUE THREAD

**Issue by gourab-aiplanet** [langfuse/langfuse#2363] opened 2024-06-18 11:08 UTC
### Describe the bug

The usage and cost calculation for the GPT-4 model is not working as expected. Despite passing the model parameter correctly, Langfuse fails to compute the usage and cost.

### To reproduce

`generation = langfuse.generation(
        trace_id=trace.id,
        name=f"{app_name}-{version}",
        version=version,
        start_time=generationStartTime,
        end_time=datetime.now(),
        model=model, // model value 'gpt-4'
        model_parameters=model_parameters
    )`

### SDK and container versions

Version: 2.33.0

### Are you interested to contribute a fix for this bug?

No

**Comment by spacepirate0001** [comment] 2024-06-25 21:16
This works fine with v2.56.1
![image](https://github.com/langfuse/langfuse/assets/6020019/4617d8b0-ad05-4e77-95e3-0cc17ca91174)

**Comment by marcklingen** [comment] 2024-06-25 22:44
I also cannot reproduce this on the current version,  does your Langfuse version include gpt-4 in the models table? Please upgrade and check again if this works. Closing for now

**Closed by marcklingen** 2024-06-25 22:44 UTC
Labels: 🐞❔ unconfirmed bug
