### ISSUE TITLE
bug: Unable to navigate between pages in Organization Members

### ISSUE THREAD

**Issue by aiakubovich** [langfuse/langfuse#3382] opened 2024-09-17 08:03 UTC
### Describe the bug

when i click next page (mark in yellow bellow):
![image](https://github.com/user-attachments/assets/6bb9dc5e-4cf3-405c-a295-4f5354e7e352)
langfuse re-address to second page for one second and next for some reasone sending back to first page 

### To reproduce

add 15 members to org. Go to Organization Members and try to click on next page button 

### SDK and container versions

2.78.0

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment] 2024-09-17 15:56
Can you share a video? I cannot reproduce this unfortunately

https://github.com/user-attachments/assets/dde8a36b-3961-4a6e-a426-44f80b547ad7

**Comment by marcklingen** [comment] 2024-09-23 09:26
Closing this issue for now, as I cannot reproduce it. It would be helpful if you could share a Loom recording of the problem.

**Closed by marcklingen** 2024-09-23 09:26 UTC
Labels: ui, 🐞❔ unconfirmed bug, feat-auth
