### ISSUE TITLE
bug: Cannot find module '@prisma/client' or its corresponding type declarations.

### ISSUE THREAD

**Issue by lizhang2024** [langfuse/langfuse#3391] opened 2024-09-18 06:26 UTC
### Describe the bug

50.27 web:build: ./src/ee/features/evals/components/template-form.tsx:21:35
50.27 web:build: Type error: Cannot find module '@prisma/client' or its corresponding type declarations.
50.27 web:build: 
50.27 web:build:   19 | import { extractVariables, getIsCharOrUnderscore } from "@/src/utils/string";
50.27 web:build:   20 | import router from "next/router";
50.27 web:build: > 21 | import { type EvalTemplate } from "@prisma/client";
50.27 web:build:      |                                   ^
50.27 web:build:   22 | import {
50.27 web:build:   23 |   ModelParameters,
50.27 web:build:   24 |   type ModelParamsContext,
50.38 web:build:  ELIFECYCLE  Command failed with exit code 1.
50.40 web:build: ERROR: command finished with error: command (/app/web) /usr/local/bin/pnpm run build exited (1)
50.41 web#build: command (/app/web) /usr/local/bin/pnpm run build exited (1)

### To reproduce

build with the commit 9ae0708cca4462758e244fbc0b7c0cb442e302d4

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment] 2024-09-18 07:12
Thanks for sharing. This passed all tests, thus it builds generally.

can you share how you try to build Langfuse?

**Comment by lizhang2024** [comment] 2024-09-18 08:02
Thanks for your quick reply. I use the docker-compose to build.
docker-compose -f ./docker-compose.build.yml up -d --build

**Comment by marcklingen** [comment] 2024-09-18 10:12
I cannot reproduce this issue, the following worked well for me. Can you share more details?

```bash
git clone https://github.com/langfuse/langfuse.git
cd langfuse
docker-compose -f ./docker-compose.build.yml up -d --build
```

**Comment by lizhang2024** [comment] 2024-09-19 00:17
docker-compose -f ./docker-compose.build.yml up -d --build
[+] Building 62.1s (34/47)                                                                                                                                                                             docker:default
 => [server internal] load build definition from Dockerfile                                                                                                                                                      0.0s
 => => transferring dockerfile: 2.74kB                                                                                                                                                                           0.0s
 => [worker internal] load build definition from Dockerfile                                                                                                                                                      0.0s
 => => transferring dockerfile: 1.42kB                                                                                                                                                                           0.0s
 => [worker internal] load metadata for docker.io/library/node:20-alpine                                                                                                                                         0.7s
 => [worker internal] load .dockerignore                                                                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                                                                  0.0s
 => [server internal] load .dockerignore                                                                                                                                                                         0.0s
 => => transferring context: 2B                                                                                                                                                                                  0.0s
 => [server alpine 1/2] FROM docker.io/library/node:20-alpine@sha256:2d07db07a2df6830718ae2a47db6fedce6745f5bcd174c398f2acdda90a11c03                                                                            0.0s
 => [worker internal] load build context                                                                                                                                                                        18.2s
 => => transferring context: 17.50MB                                                                                                                                                                            17.9s
 => [server internal] load build context                                                                                                                                                                        18.2s
 => => transferring context: 17.50MB                                                                                                                                                                            17.9s
 => CACHED [server alpine 2/2] RUN apk update && apk upgrade --no-cache libcrypto3 libssl3 libc6-compat                                                                                                          0.0s
 => CACHED [server base 1/3] RUN npm install turbo --global                                                                                                                                                      0.0s
 => CACHED [server base 2/3] RUN corepack enable                                                                                                                                                                 0.0s
 => CACHED [server base 3/3] RUN corepack prepare pnpm@8.15.5 --activate                                                                                                                                         0.0s
 => CACHED [server runner 1/4] WORKDIR /app                                                                                                                                                                      0.0s
 => CACHED [worker runner 2/4] RUN addgroup --system --gid 1001 expressjs                                                                                                                                        0.0s
 => CACHED [worker runner 3/4] RUN adduser --system --uid 1001 expressjs                                                                                                                                         0.0s
 => CACHED [worker pruner 2/3] COPY . .                                                                                                                                                                          0.0s
 => CACHED [worker pruner 3/3] RUN turbo prune --scope=worker --docker                                                                                                                                           0.0s
 => CACHED [worker builder 2/7] COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml                                                                                                                      0.0s
 => CACHED [worker builder 3/7] COPY --from=pruner /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml                                                                                                            0.0s
 => CACHED [worker builder 4/7] COPY --from=pruner /app/out/json/ .                                                                                                                                              0.0s
 => CACHED [worker builder 5/7] RUN pnpm install --frozen-lockfile                                                                                                                                               0.0s
 => CACHED [worker builder 6/7] COPY --from=pruner /app/out/full/ .                                                                                                                                              0.0s
 => CACHED [worker builder 7/7] RUN turbo run build --filter=worker...                                                                                                                                           0.0s
 => CACHED [worker runner 4/4] COPY --from=builder --chown=expressjs:expressjs /app .                                                                                                                            0.0s
 => CACHED [server pruner 2/3] COPY . .                                                                                                                                                                          0.0s
 => CACHED [server pruner 3/3] RUN turbo prune --scope=web --docker                                                                                                                                              0.0s
 => CACHED [server builder 2/8] COPY --from=pruner /app/out/pnpm-lock.yaml ./pnpm-lock.yaml                                                                                                                      0.0s
 => CACHED [server builder 3/8] COPY --from=pruner /app/out/pnpm-workspace.yaml ./pnpm-workspace.yaml                                                                                                            0.0s
 => CACHED [server builder 4/8] COPY --from=pruner /app/out/json/ .                                                                                                                                              0.0s
 => CACHED [server builder 5/8] RUN pnpm install --frozen-lockfile                                                                                                                                               0.0s
 => CACHED [server builder 6/8] COPY --from=pruner /app/out/full/ .                                                                                                                                              0.0s
 => CACHED [server builder 7/8] RUN rm -f ./web/src/middleware.ts                                                                                                                                                0.0s
 => ERROR [server builder 8/8] RUN turbo run build --filter=web                                                                                                                                                 43.0s
 => [worker] exporting to image                                                                                                                                                                                  0.0s
 => => exporting layers                                                                                                                                                                                          0.0s
 => => writing image sha256:caca506b89628cf0a618054bab17e1e1bd4d0c2fbff9ab9198dfb847d880b3c6                                                                                                                     0.0s
 => => naming to docker.io/library/evaluation_dashboard-worker                                                                                                                                                   0.0s
------                                                                                                                                                                                                                
 > [server builder 8/8] RUN turbo run build --filter=web:                                                                                                                                                             
0.359                                                                                                                                                                                                                 
0.359 Attention:                                                                                                                                                                                                      
0.359 Turborepo now collects completely anonymous telemetry regarding usage.                                                                                                                                          
0.359 This information is used to shape the Turborepo roadmap and prioritize features.                                                                                                                                
0.359 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
0.359 https://turbo.build/repo/docs/telemetry
0.359 
0.489 • Packages in scope: web
0.489 • Running build in 1 packages
0.489 • Remote caching disabled
0.492 @langfuse/shared:db:generate: cache bypass, force executing e92d77e91272b106
0.592 @langfuse/shared:db:generate: ! The local project doesn't define a 'packageManager' field. Corepack will now add one referencing pnpm@8.15.5+sha512.b051a32c7e695833b84926d3b29b8cca57254b589f0649d899c6e9d0edb670b91ec7e2a43459bae73759bb5ce619c3266f116bf931ce22d1ef1759a7e45aa96f.
0.592 @langfuse/shared:db:generate: ! For more details about this field, consult the documentation at https://nodejs.org/api/packages.html#packagemanager
0.592 @langfuse/shared:db:generate: 
1.052 @langfuse/shared:db:generate: 
1.052 @langfuse/shared:db:generate: > @langfuse/shared@1.0.0 db:generate /app/packages/shared
1.053 @langfuse/shared:db:generate: > dotenv -e ../../.env -- npx prisma generate
1.053 @langfuse/shared:db:generate: 
2.353 @langfuse/shared:db:generate: Prisma schema loaded from prisma/schema.prisma
5.252 @langfuse/shared:db:generate: ERD generator is disabled
5.475 @langfuse/shared:db:generate: 
5.475 @langfuse/shared:db:generate: ✔ Generated Prisma Client (v5.12.1) to ./../../node_modules/.pnpm/@prisma+client@5.12.1_prisma@5.12.1/node_modules/@prisma/client in 387ms
5.475 @langfuse/shared:db:generate: 
5.475 @langfuse/shared:db:generate: ✔ Generated Entity-relationship-diagram (1.11.2) to ./prisma/database.svg in 107ms
5.475 @langfuse/shared:db:generate: 
5.475 @langfuse/shared:db:generate: ✔ Generated Kysely types (1.8.0) to ./prisma/generated in 210ms
5.475 @langfuse/shared:db:generate: 
5.475 @langfuse/shared:db:generate: Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
5.475 @langfuse/shared:db:generate: ```
5.475 @langfuse/shared:db:generate: import { PrismaClient } from '@prisma/client'
5.475 @langfuse/shared:db:generate: const prisma = new PrismaClient()
5.475 @langfuse/shared:db:generate: ```
5.475 @langfuse/shared:db:generate: or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
5.475 @langfuse/shared:db:generate: ```
5.475 @langfuse/shared:db:generate: import { PrismaClient } from '@prisma/client/edge'
5.475 @langfuse/shared:db:generate: const prisma = new PrismaClient()
5.475 @langfuse/shared:db:generate: ```
5.475 @langfuse/shared:db:generate: 
5.475 @langfuse/shared:db:generate: See other ways of importing Prisma Client: http://pris.ly/d/importing-client
5.475 @langfuse/shared:db:generate: 
5.475 @langfuse/shared:db:generate: ┌────────────────────────────────────────────────────────────────┐
5.475 @langfuse/shared:db:generate: │  Supercharge your Prisma Client with global database caching,  │
5.475 @langfuse/shared:db:generate: │  scalable connection pooling and real-time database events.    │
5.475 @langfuse/shared:db:generate: │  Explore Prisma Accelerate: https://pris.ly/cli/-accelerate    │
5.475 @langfuse/shared:db:generate: │  Explore Prisma Pulse: https://pris.ly/cli/-pulse              │
5.475 @langfuse/shared:db:generate: └────────────────────────────────────────────────────────────────┘
5.475 @langfuse/shared:db:generate: 
5.715 @langfuse/shared:build: cache miss, executing 09f8ac4a0574079c
6.256 @langfuse/shared:build: 
6.256 @langfuse/shared:build: > @langfuse/shared@1.0.0 build /app/packages/shared
6.256 @langfuse/shared:build: > tsc
6.256 @langfuse/shared:build: 
10.64 @langfuse/ee:build: cache miss, executing 661c092feb846354
11.19 @langfuse/ee:build: 
11.19 @langfuse/ee:build: > @langfuse/ee@1.0.0 build /app/ee
11.19 @langfuse/ee:build: > tsc
11.19 @langfuse/ee:build: 
14.13 web:build: cache miss, executing eb15c54bcd4f48d7
14.69 web:build: 
14.69 web:build: > web@2.33.0 build /app/web
14.69 web:build: > pnpm run copy-openapi-spec && INLINE_RUNTIME_CHUNK=false dotenv -e ../.env -- next build
14.69 web:build: 
15.24 web:build: 
15.24 web:build: > web@2.33.0 copy-openapi-spec /app/web
15.24 web:build: > cp generated/openapi-client/openapi.yml public/openapi-client.yml && cp generated/openapi-server/openapi.yml public/openapi-server.yml
15.24 web:build: 
17.02 web:build:   ▲ Next.js 14.2.1
17.02 web:build: 
17.02 web:build:    Linting and checking validity of types ...
35.72 web:build: 
35.72 web:build: ./src/components/LangfuseLogo.tsx
35.72 web:build: 3:10  Warning: 'VERSION' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 27:3  Warning: 'version' is assigned a value but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 
35.72 web:build: ./src/components/layouts/layout.tsx
35.72 web:build: 9:10  Warning: 'MessageSquarePlus' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 15:3  Warning: 'AvatarImage' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 19:10  Warning: 'FeedbackButtonWrapper' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 23:10  Warning: 'LangfuseLogo' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 
35.72 web:build: ./src/components/layouts/routes.ts
35.72 web:build: 6:3  Warning: 'LifeBuoy' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 10:3  Warning: 'UsersIcon' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 12:3  Warning: 'LibraryBig' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 13:3  Warning: 'TerminalIcon' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 14:3  Warning: 'Lightbulb' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 
35.72 web:build: ./src/components/layouts/spinner.tsx
35.72 web:build: 1:10  Warning: 'LangfuseIcon' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 
35.72 web:build: ./src/ee/features/evals/components/eval-config-form.tsx
35.72 web:build: 44:8  Warning: 'TableLink' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 
35.72 web:build: ./src/ee/features/evals/components/template-form.tsx
35.72 web:build: 2:10  Warning: 'useCallback' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 17:15  Warning: 'RouterOutputs' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 
35.72 web:build: ./src/features/column-visibility/hooks/useColumnVisibility.ts
35.72 web:build: 39:6  Warning: React Hook useEffect has a missing dependency: 'initialVisibilityState'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps
35.72 web:build: 
35.72 web:build: ./src/features/datasets/components/NewDatasetItemButton.tsx
35.72 web:build: 7:3  Warning: 'DialogTitle' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 
35.72 web:build: ./src/features/email/templates/ProjectInvitation.tsx
35.72 web:build: 10:3  Warning: 'Img' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 
35.72 web:build: ./src/features/prompts/components/prompt-detail.tsx
35.72 web:build: 1:18  Warning: 'Terminal' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 17:10  Warning: 'PromotePrompt' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 
35.72 web:build: ./src/pages/auth/sign-in.tsx
35.72 web:build: 2:10  Warning: 'LangfuseIcon' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 
35.72 web:build: ./src/pages/auth/sign-up.tsx
35.72 web:build: 20:10  Warning: 'LangfuseIcon' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 
35.72 web:build: ./src/pages/onboarding.tsx
35.72 web:build: 18:10  Warning: 'LangfuseIcon' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 
35.72 web:build: ./src/pages/project/[projectId]/index.tsx
35.72 web:build: 4:10  Warning: 'GenerationLatencyChart' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 5:10  Warning: 'ChartScores' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 7:10  Warning: 'MetricTable' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 9:10  Warning: 'ModelUsageChart' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 11:10  Warning: 'UserChart' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 27:10  Warning: 'FeedbackButtonWrapper' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 28:10  Warning: 'BarChart2' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 29:10  Warning: 'Button' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 34:10  Warning: 'LatencyTables' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 123:9  Warning: 'agg' is assigned a value but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 
35.72 web:build: ./src/pages/project/[projectId]/settings.tsx
35.72 web:build: 3:10  Warning: 'SiOpenai' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 7:10  Warning: 'Code' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 7:16  Warning: 'Bird' is defined but never used.  @typescript-eslint/no-unused-vars
35.72 web:build: 
35.72 web:build: info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
42.59 web:build: Failed to compile.
42.59 web:build: 
42.59 web:build: ./src/ee/features/evals/components/template-form.tsx:21:35
42.59 web:build: Type error: Cannot find module '@prisma/client' or its corresponding type declarations.
42.59 web:build: 
42.59 web:build:   19 | import { extractVariables, getIsCharOrUnderscore } from "@/src/utils/string";
42.59 web:build:   20 | import router from "next/router";
42.59 web:build: > 21 | import { type EvalTemplate } from "@prisma/client";
42.59 web:build:      |                                   ^
42.59 web:build:   22 | import {
42.59 web:build:   23 |   ModelParameters,
42.59 web:build:   24 |   type ModelParamsContext,
42.69 web:build:  ELIFECYCLE  Command failed with exit code 1.
42.70 web:build: ERROR: command finished with error: command (/app/web) /usr/local/bin/pnpm run build exited (1)
42.71 web#build: command (/app/web) /usr/local/bin/pnpm run build exited (1)
42.71 
42.71  Tasks:    3 successful, 4 total
42.71 Cached:    0 cached, 4 total
42.71   Time:    42.343s 
42.71 Failed:    web#build
42.71 
42.72  ERROR  run failed: command  exited (1)
------
failed to solve: process "/bin/sh -c turbo run build --filter=web" did not complete successfully: exit code: 1

**Comment by maxdeichmann** [comment] 2024-09-19 07:11
@lizhang2024 i think we fixed this issue already. Could you maybe pull the latest commit from main and build again?

**Comment by marcklingen** [comment] 2024-09-23 09:36
Did this resolve the issue for you?

**Comment by marcklingen** [comment] 2024-09-30 23:55
Can you confirm that this fixed the issue for you? I'd like to either help fix this or close the issue as stale

**Comment by marcklingen** [comment] 2024-10-10 05:40
closing as this is fixed, please reopen in case you still encounter this issue after updating your application

**Closed by marcklingen** 2024-10-10 05:40 UTC
Labels: Docker, 🐞❔ unconfirmed bug
