### ISSUE TITLE
bug: bad stack-trace when trying to add score to non-existing trace-id

### ISSUE THREAD

**Issue by Bl4ckEnd** [langfuse/langfuse#474] opened 2023-11-13 09:38 UTC
### Describe the bug

I am currently using ragas to evaluate my completions and want to add the scores to langfuse. While debugging, I accidentally used a trace_id that does not exist in our langfuse project. The issue is that in this case langfuse raises a pydantic error instead of simply saying that the trace_id does not exist.

![image](https://github.com/langfuse/langfuse/assets/26367290/b9b18589-0407-4b7d-85c9-fd7460b8a9e5)

I suggest catching this error with a useful error message.

### To reproduce

use a non-existing trace_id when adding a score to langfuse.

**Comment by maxdeichmann** [comment] 2023-11-13 10:00
@Bl4ckEnd thanks for the issue. We are currently looking to improve this.

**Comment by marcklingen** [comment] 2023-11-20 12:17
Thanks for reporting, we've made changes to the ingestion APIs and will fix this shortly

**Comment by maxdeichmann** [comment] 2023-11-23 23:59
@Bl4ckEnd thanks again for reporting this. The issue is resolved with the latest Python SDK + server version

**Closed by maxdeichmann** 2023-11-23 23:59 UTC
Labels: bug, Python SDK, High priority
