### ISSUE TITLE
bug: reading openai.beta.chat.completions.stream fails if not awaited

### ISSUE THREAD

**Issue by piotrbaldych-cr** [langfuse/langfuse#4571] opened 2024-12-04 14:38 UTC
### Describe the bug

The issue came up when trying to use observeOpenAI with CopilotKit. In their implementation the openai.beta.chat.completions.stream is not awaited. Using the observeOpenAI casues errors:

```
Error in event source callback TypeError: stream is not async iterable
```

### To reproduce

```
import { observeOpenAI } from "langfuse";
import { OpenAI } from "openai";
import dotenv from "dotenv";

dotenv.config();

const openai = new OpenAI();

const observer = observeOpenAI(openai);

console.log("OpenAI: ");

const openaiStream = openai.beta.chat.completions.stream({
  model: "gpt-4",
  stream: true,
  messages: [{ role: "user", content: "text" }],
  stream_options: { include_usage: true }
});

// this works
for await (const chunk of openaiStream) {
  process.stdout.write(chunk.choices[0]?.delta?.content || "");
}

console.log("\n\nOpenAI with await: ");

const awaitedOpenaiStream = await openai.beta.chat.completions.stream({
  model: "gpt-4",
  stream: true,
  messages: [{ role: "user", content: "text" }],
  stream_options: { include_usage: true }
});

// this works
for await (const chunk of awaitedOpenaiStream) {
  process.stdout.write(chunk.choices[0]?.delta?.content || "");
}

console.log("\n\nObserver with await: ");

const awaitedObserverStream = await observer.beta.chat.completions.stream({
  model: "gpt-4",
  stream: true,
  messages: [{ role: "user", content: "text" }],
  stream_options: { include_usage: true }
});

// this works
for await (const chunk of awaitedObserverStream) {
  process.stdout.write(chunk.choices[0]?.delta?.content || "");
}

console.log("\n\nObserver without await: ");

const observerStream = observer.beta.chat.completions.stream({
  model: "gpt-4",
  stream: true,
  messages: [{ role: "user", content: "text" }],
  stream_options: { include_usage: true }
});

// this doesn't work
for await (const chunk of observerStream) {
  process.stdout.write(chunk.choices[0]?.delta?.content || "");
}
```

### SDK and container versions

"langfuse": "3.31.1",

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment] 2024-12-05 08:36
Thanks for raising this, this is a duplicate of https://github.com/langfuse/langfuse/issues/4033, closing this as we track progress there 👍🏾

**Closed by hassiebp** 2024-12-05 08:36 UTC
Labels: 🐞❔ unconfirmed bug
