### ISSUE TITLE
bug: 100% memory and CPU consumption when setting up the dev environment

### ISSUE THREAD

**Issue by faresbouzayen** [langfuse/langfuse#3932] opened 2024-10-27 14:23 UTC
### Describe the bug

I expect the dev env to be working reasonably

### To reproduce

setup the dev env

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment] 2024-11-04 09:30
Closing this issue for now as I cannot reproduce this, please share more details on your setup if you still encounter these problems

**Closed by marcklingen** 2024-11-04 09:30 UTC
Labels: 🐞❔ unconfirmed bug

**Comment by okaeiz** [comment] 2025-05-18 11:24
I am also experiencing this issue.
