### ISSUE TITLE
Langfuse was not able to parse the LLM model

### ISSUE THREAD

**Issue by medurisaisirisha** [langfuse/langfuse#1976] opened 2024-05-04 05:38 UTC
### Describe the bug

When i run langfus ei am getting this error

### To reproduce

Tried to route receipe related to Groq and used ollama in my local. Whenever i try to run its giving this error

### Are you interested to contribute a fix for this bug?

Yes

**Comment by marcklingen** [comment] 2024-05-05 15:32
thanks for reporting this, is this a duplicate of https://github.com/langfuse/langfuse/issues/1798 ? (using langchain python)

**Comment by medurisaisirisha** [comment] 2024-05-05 23:22
Hey,

Looks like this issue has raised because of slowness and it started working
after 1 hr.

Regards,
Sai Sirisha

**Closed** 2024-05-05 23:24 UTC
Labels: 🐞❔ unconfirmed bug
