### ISSUE TITLE
bug: DNS resolution error, markdown render image: if image's url of hostname not set the ipv6 address wiil let the image-url is invaild

### ISSUE THREAD

**Issue by shizheng163** [langfuse/langfuse#3015] opened 2024-08-22 15:09 UTC
### Describe the bug

My Image url is start with https://bj.bcebos.com
when i touch the preview could not get any response
![image](https://github.com/user-attachments/assets/85bf4e05-b497-413b-8344-1a036214f0c6)

I trace the http api, notice the validate interface response has invaild info.

API: api/trpc/utilities.validateImgUrl

response: 
```
{"result":{"data":{"json":{"isValid":false}}}}
```

![img_v3_02e0_fff31f6a-6df7-421e-9f99-4cd87d6eeecg](https://github.com/user-attachments/assets/490d546f-92c8-4f94-821f-ffbf099fa3fc)

I viewed the src code, found the hostname must has ipv6 and. ipv4 at the same time, otherwise will throw the `DNS resolution error`

![img_v3_02e0_6728ed3f-adca-4654-8a4c-6ad0449629fg](https://github.com/user-attachments/assets/11375f2c-af36-4f68-8a78-a79c779dfe9f)

The LLM give me a Reference information

```
这个错误信息表示在尝试通过 DNS 解析 bj.bcebos.com 的 AAAA 记录（IPv6 地址）时没有找到任何数据。错误是由 Node.js 的内部 DNS 模块抛出的，并且它返回了一个特殊的错误码 ENODATA。

ENODATA 错误通常意味着 DNS 服务器响应了一个 NXDATA 或者根本没有返回 AAAA 记录的数据。这可能是因为以下原因：

域名不存在：确保 bj.bcebos.com 是一个有效的域名并且正确拼写。
没有 AAAA 记录：该域名可能只配置了 IPv4 地址（A 记录），而没有配置 IPv6 地址（AAAA 记录）。你可以尝试使用 A 记录查询（queryA）来获取 IPv4 地址。
DNS 配置问题：可能是 DNS 服务器本身的配置问题，或者你的网络环境中的 DNS 设置有问题。
网络问题：有可能是网络连接问题导致无法成功从 DNS 服务器获取数据。
```

### To reproduce

use not has ipv6 hostname? 

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment] 2024-08-22 15:32
probably either an ipv6 or ipv4 hostname should be enough here, @marliessophie wdyt?

**Comment by marliessophie** [comment] 2024-08-22 15:33
that's fair, will change 👍

**Comment by shizheng163** [comment] 2024-09-06 08:22
@marliessophie hi, When can it be fixed? , thank you

**Comment by marliessophie** [comment] 2024-09-06 08:39
Hi @shizheng163, sorry for the delay. I'll look into this by beginning of next week, thanks for the ping 👍

**Comment by shizheng163** [comment] 2024-09-20 03:07
Hi, is it fixed? I didn’t find any mention of #3016 in the release.
@marliessophie

**Comment by marliessophie** [comment] 2024-09-20 06:56
Hi @shizheng163, as per the [2.79.0 release notes](https://github.com/langfuse/langfuse/releases/tag/v2.79.0) the issue should be fixed. Please reach out should you have further questions. Thanks for the patience!

**Comment by shizheng163** [comment] 2024-09-20 14:12
I already upgrade  to 2.80.0, but still has follow error. @marliessophie 

```
9522156f5558","id":"25678a94-144d-40aa-9dc1-4440b5b23a4a","endTime":"2024-09-20T14:01:52.589594Z"}}
DNS resolution error: Error: queryAaaa ENODATA bj.bcebos.com
at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:291:17)
at QueryReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
errno: undefined,
code: 'ENODATA',
syscall: 'queryAaaa',
hostname: 'bj.bcebos.com'
}
2024-09-20T14:01:56.002Z info handling single event e841c145-0faf-4669-b96c-aa9e628e9340 of type span-update: {"body":{"traceId":"8edf5bf3-251f-43d8-9e2f-9522156f5558","id":"ec4588d2-9eb6-4821-a6a6-24500bf3346e","endTime":"2024-09-20T14:01:55.944198Z"}}
DNS resolution error: Error: queryAaaa ENODATA bj.bcebos.com
at QueryReqWrap.onresolve [as oncomplete] (node:internal/dns/promises:291:17)
at QueryReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
errno: undefined,
code: 'ENODATA',
syscall: 'queryAaaa',
hostname: 'bj.bcebos.com'
}
```

the fix code maybe need to modify the follow code ?
![image](https://github.com/user-attachments/assets/26f89217-c4f6-4221-9514-b5205c5bebb5)

**Comment by marliessophie** [comment] 2024-09-20 14:16
Thanks for re-reporting. Apologies, I had misunderstood your original comment and mis-located the root cause. I'll have another look and fix on the way by tomorrow hopefully, and it will be included in the next release. Sorry about the delay on this and thanks for re-explaining the issue.

**Closed** 2024-09-23 14:12 UTC
