### ISSUE TITLE
bug: LangChain+ChatGroq Streaming+Langfuse Not Recording Token Usage

### ISSUE THREAD

**Issue by Lorentzo92** [langfuse/langfuse#3265] opened 2024-09-08 21:07 UTC
### Describe the bug

languse does not record input and output tokens when streaming chatgrop with langchain. Invoke works.

### To reproduce

execute code from here

https://python.langchain.com/v0.2/api_reference/groq/chat_models/langchain_groq.chat_models.ChatGroq.html

### Are you interested to contribute a fix for this bug?

Yes

**Comment by Lorentzo92** [comment] 2024-09-09 06:36
+ i confirm the bug is present just by running the stream/astream method from the langsfuse doc:
https://langfuse.com/docs/integrations/langchain/example-python

**Comment by marcklingen** [comment] 2024-09-11 10:58
thanks for sharing!

many model providers (including groq) do not include token counts in their response when streaming. for langfuse to support token counts, this needs to be supported by the model provider + langchain.

For reference:
- https://api.python.langchain.com/en/latest/chat_models/langchain_groq.chat_models.ChatGroq.html
- https://console.groq.com/docs/api-reference#chat-create

which model do you use via groq?

**Comment by Lorentzo92** [comment] 2024-09-11 15:09
From groq i am using:
- llama-3.1-70b-versatile
- llama3-groq-70b-8192-tool-use-preview

However i am seeing the same issue using ChatOpenAI from langchain_openai, any model generates zero token.

Thanks.

**Comment by marcklingen** [comment] 2024-09-11 16:40
thanks for sharing!

> However i am seeing the same issue using ChatOpenAI from langchain_openai, any model generates zero token.

are you on the latest langchain and langfuse sdk versions?

**Comment by Lorentzo92** [comment] 2024-09-11 18:47
Checked the versions, i was behind a couple of minor versions. The issue with langchain_openai is that they changed the default param stream_usage: bool = False, so setting to true does the job.
While for chat groq now it seems to stream the usage as well :D

**Comment by marcklingen** [comment] 2024-09-11 20:33
> Checked the versions, i was behind a couple of minor versions. The issue with langchain_openai is that they changed the default param stream_usage: bool = False, so setting to true does the job. While for chat groq now it seems to stream the usage as well :D

great to hear. this works now as expected?

**Comment by marcklingen** [comment] 2024-09-18 12:59
Closing this now as I understand that this all works as expected now. Please update this thread in case the issue is ongoing

**Closed by marcklingen** 2024-09-18 12:59 UTC
Labels: 🐞❔ unconfirmed bug
