### ISSUE TITLE
bug(self-hosted-media): Minio URLs cannot be resolved when fetching assets

### ISSUE THREAD

**Issue by backface** [langfuse/langfuse#4369] opened 2024-11-21 20:11 UTC
### Describe the bug

Can you provide a working example of a self-hosted instance's media upload configuration through LANGFUSE_S3_MEDIA_UPLOAD_*? 

First off: The documentation of default values at  https://langfuse.com/docs/deployment/self-host is wrong or not up to date (For instance the default for LANGFUSE_S3_MEDIA_UPLOAD_ENABLED seems to be false in 2.92.0 but was it was indeed true in 2.91.0) but also others are not doing what expected:

### To reproduce

set (as should be the default according to the docs)

LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT=http://minio:9000  

yields (with a direct request to the API endpoint)

{'mediaId': '25510795-48f0-48eb-aa04-fb2a997042eb', 'uploadUrl': 'http://langfuse.minio:9000/langfuse/cm2btpjht00062cdm3c398y61/25510795-48f0-48eb-aa04-fb2a997042eb.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=tG9JsjoK2NNBCvNeBsVJ%2F20241121%2Flocal%2Fs3%2Faws4_request&X-Amz-Date=20241121T194721Z&X-Amz-Expires=3600&X-Amz-Signature=f21106ce543d975d06a846a2493565f5848aff2b755e99f8a106033ec0fa6dc4&X-Amz-SignedHeaders=content-length%3Bcontent-type%3Bhost%3Bx-amz-checksum-sha256&x-id=PutObject'}

and via SDK

ERROR:langfuse._task_manager.media_manager:Error uploading media: HTTPConnectionPool(host='langfuse.minio', port=9000): Max retries exceeded with url: /langfuse/cm2btpjht00062cdm3c398y61/3564bb2b-9921-4a7a-afaf-5423264cb9cc.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=tG9JsjoK2NNBCvNeBsVJ%2F20241121%2Flocal%2Fs3%2Faws4_request&X-Amz-Date=20241121T194721Z&X-Amz-Expires=3600&X-Amz-Signature=693b40db691c944561a99a5cf78d5bb7d193dc7e6b931ffadeaac3aaf43786a1&X-Amz-SignedHeaders=content-length%3Bcontent-type%3Bhost%3Bx-amz-checksum-sha256&x-id=PutObject (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f940825d190>: Failed to resolve 'langfuse.minio' ([Errno -2] Name or service not known)"))

not exactly the endpoint provided.

Leaving it at the default still points to a langfuse AWS endpoint:

API

{'mediaId': '25510795-48f0-48eb-aa04-fb2a997042eb', 'uploadUrl': 'https://langfuse.s3.local.amazonaws.com/langfuse/cm2btpjht00062cdm3c398y61/25510795-48f0-48eb-aa04-fb2a997042eb.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=tG9JsjoK2NNBCvNeBsVJ%2F20241121%2Flocal%2Fs3%2Faws4_request&X-Amz-Date=20241121T200401Z&X-Amz-Expires=3600&X-Amz-Signature=e42b81be16853989ea860cbc9eba3362570cb716194f54377e4e8271234657d2&X-Amz-SignedHeaders=content-length%3Bcontent-type%3Bhost%3Bx-amz-checksum-sha256&x-id=PutObject'}

SDK

ERROR:langfuse._task_manager.media_manager:Error uploading media: HTTPSConnectionPool(host='langfuse.s3.local.amazonaws.com', port=443): Max retries exceeded with url: /langfuse/cm2btpjht00062cdm3c398y61/7417da03-7dc1-46fd-b47f-9e181d05b0e9.jpeg?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=tG9JsjoK2NNBCvNeBsVJ%2F20241121%2Flocal%2Fs3%2Faws4_request&X-Amz-Date=20241121T195031Z&X-Amz-Expires=3600&X-Amz-Signature=5458d81864330a0f0af7213f0fb5c17134f8630a05a9da7fdc4d13045fb3fa79&X-Amz-SignedHeaders=content-length%3Bcontent-type%3Bhost%3Bx-amz-checksum-sha256&x-id=PutObject (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f5f796f8b10>: Failed to resolve 'langfuse.s3.local.amazonaws.com' ([Errno -2] Name or service not known)"))

I think the other options such as for bucket end prefix might also not exactly do what they claim to do, but at this point there's no way to test it ...

### SDK and container versions

Latest releases
langfuse docker image 2.92.0 OSS
langfuse-python SDK 2.52

### Are you interested to contribute a fix for this bug?

No

**Comment by hassiebp** [comment] 2024-11-22 12:23
Hi @backface - this looks like an issue in your networking setup, the `minio` host cannot be resolved. Could you please try to reach it from inside your running langfuse container with `ping minio`?

**Comment by backface** [comment] 2024-11-22 12:50
@hassiebp Yes, I confirm I can ping the minio and reach it from within and outside the containers!

again: if I set the env var to LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT=http://minio:9000/
it tries to connect to http://langfuse.minio:9000/
(where "langfuse" is the bucket name!)

if I leave it empty it tries to connect to:  https://langfuse.s3.local.amazonaws.com//
where "langfuse" is the bucket name, and "local" is the region (and according to the docs also should be http://minio:9000/)

So, tracking it down a bit further, it seems you are adding LANGFUSE_S3_MEDIA_UPLOAD_BUCKET as a subdomain to the endpoint that is parsed from LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT. But obviously, that does not exist here. 
Nothing wrong with my networking or Docker setup.

**Comment by wzunknown** [comment] 2024-11-22 18:37
I met a similar problem. I have tried the docker-compose.v3preview.yml and docker-compose.yml adding minio setup from main branch. The error message is:
```
Error uploading media: HTTPConnectionPool(host='minio', port=9000): Max retries exceeded with url: /langfuse/media/cm3sjtduq0006na1bsv9ylj5l/58e3bccd-3aed-41d4-b6de-a2fd54fdd75a.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=minio%2F20241122%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20241122T095423Z&X-Amz-Expires=3600&X-Amz-Signature=9a286357f1c7d1f8d8e86541dcd0cc86c23253bf1a05b3dc0051f3196418ea0b&X-Amz-SignedHeaders=content-length%3Bcontent-type%3Bhost%3Bx-amz-checksum-sha256&x-id=PutObject (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x7f9d31d3bb50>: Failed to resolve 'minio' ([Errno -3] Temporary failure in name resolution)"))
```
I can ping `minio` in langfuse-worker.

**Comment by dprokhorov17** [comment] 2024-11-25 09:47
Hello,

how to setup this on Azure when self hosting there?

**Comment by hassiebp** [comment] 2024-11-25 11:13
@backface @wzunknown Have you created a `langfuse` bucket in your minio instance prior to service startup? 

See here in our V3 preview docker-compose file how we ensure that the `langfuse` named bucket exists prior to startup: https://github.com/langfuse/langfuse/blob/f91cf1ca650ada964a6c560fce94b63b3e9e4141/docker-compose.v3preview.yml#L91

@dprokhorov17 We are also currently working on Azure support, feel free to keep an eye on this PR to track progress: https://github.com/langfuse/langfuse/pull/4386

**Comment by backface** [comment] 2024-11-25 12:09
@hassiebp I have a different startup command, but I can confirm that the bucket and the directory exist. 

What does not exist, however - and I repeat it here again -  is a DNS for "langfuse.minio" (or bucketname.minio in that case) and this is where langfuse tries to connect to!

**Comment by hassiebp** [comment] 2024-11-25 12:34
@backface could you please confirm that you have `LANGFUSE_S3_EVENT_UPLOAD_FORCE_PATH_STYLE=true` in your app?

**Comment by backface** [comment] 2024-11-25 17:46
@hassiebp I guess you mean LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE . Yes if I set LANGFUSE_S3_MEDIA_UPLOAD_FORCE_PATH_STYLE=true (which according to your docs should have the default value "true" so please update it) uploads finally work!
 
However, the next problem is that the UI refers to it with a link to "http://minio:9000/..." which of course is only reachable from within the docker container:

![Bildschirmfoto_2024-11-25_18-33-31](https://github.com/user-attachments/assets/30576858-48b1-47e2-afe0-041b76d78ae0)

(this applies to the automatic SDK uploads,  I still fail uploading from within a Python Decorator function via LangfuseMedia but that is likely a different issue)

**Comment by hassiebp** [comment] 2024-11-26 09:51
> I still fail uploading from within a Python Decorator function via LangfuseMedia but that is likely a different issue

Please check out our docs on current limitations here, please let me know if you notice anything unmentioned there: https://langfuse.com/docs/tracing-features/multi-modality#custom-attachments

> according to your docs should have the default value "true" so please update it

Thanks for pointing that out - the default values were referring to our upcoming V3 release. Updated the docs.

> However, the next problem is that the UI refers to it with a link to "http://minio:9000/..." which of course is only reachable from within the docker container:

This is indeed an issue that needs addressing, I'll update the this issue's title to reflect that. The minio host cannot be resolved when directly requesting from the browser. Meanwhile, using an S3 bucket that serves publicly reachable presigned URLs should work in the meantime.

**Comment by backface** [comment] 2024-11-26 15:31
> > I still fail uploading from within a Python Decorator function via LangfuseMedia but that is likely a different issue
> 
> Please check out our docs on current limitations here, please let me know if you notice anything unmentioned there: https://langfuse.com/docs/tracing-features/multi-modality#custom-attachments

Got it. the key difference is: Using LangfuseMedia the Python application needs direct access to the minio container! Whereas with the automatic SDK (openai) it does not, the uploads are routed through the langfuse container!

but of course, it suffers the same feat: I cannot fetch the minio URL from the UI.

**Comment by hassiebp** [comment] 2024-11-26 16:39
@Steffen911 In the presented setup, will setting the Docker host's IP and the minio port as the `LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT` work?

**Comment by Steffen911** [comment] 2024-11-26 16:45
I think so.

@backface Do you intend to connect to minio and langfuse only using localhost or do you run this on a VM? I would expect that you have an overwrite like `LANGFUSE_HOST=http://<hostname>:3000` somewhere in the environment of your langfuse client. I believe if you set the same hostname with port 9000 for the LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT it should work. It is necessary that both the Langfuse container and the SDK can reach minio under the same hostname.

**Comment by backface** [comment] 2024-11-26 17:13
@Steffen911 @hassiebp Indeed I could set LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT to localhost:9000 and it works - that is for local development, and given all the ports are open. 

But yes certainly I also intend to use it in production where the external ports are not open and everything is behind a proxy server. 

So I think it would need something like LANGFUSE_S3_MEDIA_PUBLIC_URL (external resolvable) that replaces whatever is defined in LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT (internal) when the link is rendered in the UI.

**Comment by backface** [comment] 2024-11-26 21:16
@Steffen911 Well obviously that should work and honestly, I can't say at this point whether there is an issue with it or not except that your documentation should then also say so: that it has to be a publicly resolvable hostname  - and not feature examples or default values that only can work internally (which might mislead people like me down the trail that it is also meant for internal communication)

**Comment by hassiebp** [comment] 2024-11-27 09:57
Thanks for your feedback @backface - we have updated our docs accordingly. Closing this issue as works as intended.

**Closed by hassiebp** 2024-11-27 09:57 UTC
Labels: bug, feat-multimodal-media

**Comment by jmorenoc-o** [comment] 2025-03-14 16:37
> [@Steffen911](https://github.com/Steffen911) [@hassiebp](https://github.com/hassiebp) Indeed I could set LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT to localhost:9000 and it works - that is for local development, and given all the ports are open.
> 
> But yes certainly I also intend to use it in production where the external ports are not open and everything is behind a proxy server.
> 
> So I think it would need something like LANGFUSE_S3_MEDIA_PUBLIC_URL (external resolvable) that replaces whatever is defined in LANGFUSE_S3_MEDIA_UPLOAD_ENDPOINT (internal) when the link is rendered in the UI.

I think it might be interesting to rethink this option and add a new variable for a second public URL to access Minio through a browser.

In my case we expose Langfuse and Minio through Ingress-Nginx using Kubernetes.

Currently we have the internal URL of the MinIO Kubernetes Service set to LANGFUSE_S3_BATCH_EXPORT_ENDPOINT . Example: "http://langfuse-minio:9000"

And from a browser we cannot download the trace exports because Langfuse generates the links using the URL used in LANGFUSE_S3_BATCH_EXPORT_ENDPOINT

Currently we can configure the MinIO public URL in LANGFUSE_S3_BATCH_EXPORT_ENDPOINT but we prefer that the requests between Langfuse and MinIO travel through the internal Kubernetes network and not through the Nginx balancer.

**Comment by Steffen911** [comment] 2025-03-14 16:39
@jmorenoc-o Could you create a new github discussion and tag @hassiebp and myself? Let's decouple this conversation from the ticket.

**Comment by jmorenoc-o** [comment] 2025-03-14 16:55
> [@jmorenoc-o](https://github.com/jmorenoc-o) Could you create a new github discussion and tag [@hassiebp](https://github.com/hassiebp) and myself? Let's decouple this conversation from the ticket.

Of course.

New ticket: https://github.com/orgs/langfuse/discussions/6029
