### ISSUE TITLE
bug: Tool usage is not displayed when calling llm.invoke() directly

### ISSUE THREAD

**Issue by rvndbalaji** [langfuse/langfuse#3284] opened 2024-09-10 08:40 UTC
### Describe the bug

I'm calling an LLM using `llm.invoke(tools=[....pydantic_class])` using LangChain 
Im using Claude 3.5 Sonnet and it performs tool-calling to finish the request 
In case of Claude, the assistant message content is blank, but instead the tool_calls parameter is populated with the output 

This tool call needs to be displayed but instead shows up as blank in LangFuse Trace

### To reproduce

Call LLM via LangChain

`
 response_dict = GLOBAL_LLM.invoke(messages, tools=[convert_to_anthropic_tool(StandardizedAddress)], tool_choice={'type' : 'any'},config=get_llm_config(user)).tool_calls[0]['args']
`

In the LangFuse trace,

The assitant block is displayed with a blank value (Since the .content field is blank and instead tool_calls is populated)

### SDK and container versions

LangFuse 2.78.0 OSS (Self Hosted)

### Are you interested to contribute a fix for this bug?

No

**Comment by marcklingen** [comment] 2024-09-10 13:05
thanks for reporting, which version of the python sdk do you use?

**Comment by rvndbalaji** [comment] 2024-09-11 14:55
I use `Python 3.11.1`

If it helps - 
```

google-ai-generativelanguage==0.6.4
langchain==0.2.14
langchain-anthropic==0.1.23
langchain-community==0.2.12
langchain-core==0.2.34
langchain-experimental==0.0.64
langchain-google-community==1.0.8
langchain-google-genai==1.0.4
langchain-google-vertexai==1.0.10
langchain-postgres==0.0.9
langchain-text-splitters==0.2.0
langdetect==1.0.9
langfuse==2.44.1
langgraph==0.2.12
langgraph-checkpoint==1.0.3
```

**Comment by rvndbalaji** [comment] 2024-09-16 06:35
@marcklingen  Any update on this?

**Comment by hassiebp** [comment] 2024-09-27 08:27
Thanks for reporting this @rvndbalaji! Unfortunately I cannot reproduce your issue. Could you please try adapting your example along these lines and try again?

```python
from langchain_core.tools import StructuredTool
from langchain_core.pydantic_v1 import BaseModel, Field
from langchain_anthropic import ChatAnthropic

from langfuse.callback import CallbackHandler

handler = CallbackHandler(debug=True)

llm = ChatAnthropic(model_name="claude-3-sonnet-20240229", callbacks=[handler])

class StandardizedAddress(BaseModel):
    street: str = Field(description="The street name and number")
    city: str = Field(description="The city name")
    state: str = Field(description="The state or province")
    zip_code: str = Field(description="The postal code")

# Create a tool from the StandardizedAddress model
address_tool = StructuredTool.from_function(
    func=lambda **kwargs: StandardizedAddress(**kwargs),
    name="standardize_address",
    description="Standardize the given address",
    args_schema=StandardizedAddress,
)

messages = [
    {
        "role": "user",
        "content": "Please standardize this address: 123 Main St, Springfield, IL 62701",
    }
]

llm.bind_tools([address_tool]).invoke(
    messages,
)

handler.flush()
```

[Link to resulting trace](https://us.cloud.langfuse.com/project/clth8c8yc0002ghkusbezdcdn/traces/12f70d91-f937-48c4-9865-bfd65c6aff03?observation=95ba4542-8aaf-4665-9106-490691efabc4)

**Comment by pwnywiz** [comment] 2024-10-09 11:48
> Thanks for reporting this @rvndbalaji! Unfortunately I cannot reproduce your issue. Could you please try adapting your example along these lines and try again?
> 
> ```python
> from langchain_core.tools import StructuredTool
> from langchain_core.pydantic_v1 import BaseModel, Field
> from langchain_anthropic import ChatAnthropic
> 
> from langfuse.callback import CallbackHandler
> 
> handler = CallbackHandler(debug=True)
> 
> llm = ChatAnthropic(model_name="claude-3-sonnet-20240229", callbacks=[handler])
> 
> class StandardizedAddress(BaseModel):
>     street: str = Field(description="The street name and number")
>     city: str = Field(description="The city name")
>     state: str = Field(description="The state or province")
>     zip_code: str = Field(description="The postal code")
> 
> # Create a tool from the StandardizedAddress model
> address_tool = StructuredTool.from_function(
>     func=lambda **kwargs: StandardizedAddress(**kwargs),
>     name="standardize_address",
>     description="Standardize the given address",
>     args_schema=StandardizedAddress,
> )
> 
> messages = [
>     {
>         "role": "user",
>         "content": "Please standardize this address: 123 Main St, Springfield, IL 62701",
>     }
> ]
> 
> llm.bind_tools([address_tool]).invoke(
>     messages,
> )
> 
> handler.flush()
> ```
> 
> [Link to resulting trace](https://us.cloud.langfuse.com/project/clth8c8yc0002ghkusbezdcdn/traces/12f70d91-f937-48c4-9865-bfd65c6aff03?observation=95ba4542-8aaf-4665-9106-490691efabc4)

in that minimal example, would it be possible to also trace the `address_tool` (or any tools passed to `bind_tools`) definition as llm input, in langfuse trace logs?

**Comment by hassiebp** [comment] 2024-10-09 13:43
The tool call should be already traced, and that simple tool is only providing a structured output schema. What kind of logs are you looking for exactly?

**Comment by pwnywiz** [comment] 2024-10-09 13:56
based on the [trace](https://us.cloud.langfuse.com/project/clth8c8yc0002ghkusbezdcdn/traces/12f70d91-f937-48c4-9865-bfd65c6aff03?observation=95ba4542-8aaf-4665-9106-490691efabc4) you provided, i cant see where the function was provided as input to the llm. I would like to see a "tools" with the function / schema definitions as part of the Input of the Generation trace.

**Comment by Sinnaeve** [comment] 2024-10-10 10:04
I think I have the same issue. 
In the trace you provided, we can see the LLM called the tool named 'standardize_address'.
But to do this, the LLM should have received a some instruction telling him about the possibility to use this tool and the format to do so. I would expect to see this instruction in 'generation'.

**Comment by hassiebp** [comment] 2024-10-14 23:36
Thanks, I have linked a PR with a fix. To be merged and released soon 👍🏾

**Closed** 2024-10-15 15:43 UTC
Labels: bug, sdk-python, integration-langchain
