### ISSUE TITLE
bug: Use the sum of total tokens when calculating the total cost

### ISSUE THREAD

**Issue by Manouchehri** [langfuse/langfuse#1041] opened 2024-02-01 22:25 UTC
### Describe the bug

For extremely small requests, the cost of each generation is rounded to $0.00. 

A better approach, would be calculating the total cost based on the sum of total amount of tokens * price per token. This would avoid rounding losses, and I believe this is how most LLM AIs are billed in production.

<img width="514" alt="image" src="https://github.com/langfuse/langfuse/assets/7232674/94e56a73-169f-44bb-a45b-e0c71e699947">

<img width="519" alt="image" src="https://github.com/langfuse/langfuse/assets/7232674/c13e7d73-64e3-42c2-84d5-18d5021e7337">

### To reproduce

Make a large amount of tiny requests to GPT-3.5.

**Comment by maxdeichmann** [comment] 2024-03-01 18:30
@Manouchehri thanks a lot for reporting this. I just tried to reproduce this with the latest version but everything worked well here. This is super important to us, would you mind jumping on a call and screen share? https://cal.com/mdeichmann/30min-eu

I just shipped a minor improvement where you see more scale of small USD amounts.

**Comment by marcklingen** [comment] 2024-04-08 13:28
closing this for now as we cannot reproduce this, feel free to reopen if this issue persists

**Closed by marcklingen** 2024-04-08 13:28 UTC
Labels: 🐞❔ unconfirmed bug
