### ISSUE TITLE
bug: The add model doesn't work.

### ISSUE THREAD

**Issue by LiHongYan666** [langfuse/langfuse#2700] opened 2024-07-22 02:42 UTC
### Describe the bug

I'm using langfuse to monitor one of dify's applications
Traces can be monitored, total_tokens is also there
The model I'm using is ollama's qwen:14b, configured it on the page, but it doesn't work

langfuse : 2.61.1
dify: 0.6.12
ollama: qwen:14b

![1](https://github.com/user-attachments/assets/094a70e3-6e7d-4331-9958-4262ba0fabe3)
![2](https://github.com/user-attachments/assets/87598d7e-e46a-4507-a4c5-b5283282ecbf)
![3](https://github.com/user-attachments/assets/62d94a94-83af-478a-bda2-c54d716ef908)

I just want to monitor TOTAL COST, am I misconfiguring it or is it a bug?

Thanks, looking forward to your reply!

### To reproduce

All deployed on k8s

I didn't modify the source code, just the configuration

### Are you interested to contribute a fix for this bug?

No

**Comment by alekseidolgikh** [comment] 2024-07-23 21:07
Hey team!
Is it improper implementation on Dify's side?
I see `total_tokens`, but I can't see that `model` has been passed.
I see `total_price`, but it seems like Langfuse expects `total_cost`.
WDYT?

**Comment by LiHongYan666** [comment] 2024-07-24 00:58
Total_tokens is detected in Langfuse, but after configuring the model, the billing doesn't work and the Model costs remain at 0.

**Comment by alekseidolgikh** [comment] 2024-07-24 03:21
Yes, `total_tokens` is detected in Langfuse.
I mean, if we read the documentation - https://langfuse.com/docs/model-usage-and-cost - we see that to calculate the cost, Langfuse needs `model` (in addition to `total_tokens`). Unfortunately, I can't see Dify sending `model`.
Another option - again from the documentation - https://langfuse.com/docs/model-usage-and-cost - is to directly send `total_cost`, but I can't see Dify doing this, I see only `total_price`, which is not what Langfuse expects.
Dear Langfuse developers (and @marcklingen 🫡), what do you think? Should I "blame" Dify developers? Or maybe I configured something incorrectly. I mean, I have the same problem - there are always 0.00 costs from Dify projects.

**Comment by anzax** [comment] 2024-07-25 20:26
I just configured Langfuse for Dify and found traces don't show model, here is metadata, model name is there but not mapped properly:
```
{
    "status": "normal",
    "message_id": "d8664c29-9c1a-4246-abfa-d4b02a1995f8",
    "agent_based": false,
    "from_source": "console",
    "ls_provider": "deepseek",
    "ls_model_name": "deepseek-chat",
    "conversation_id": "4cd8e8f1-37ee-4333-83cf-da137f9c0ba8",
    "from_account_id": "f0e6bb30-e26e-4e4e-af7e-07f56e7a61e0",
    "workflow_run_id": null,
    "from_end_user_id": "f0e6bb30-e26e-4e4e-af7e-07f56e7a61e0"
}
```

**Comment by marcklingen** [comment] 2024-09-18 13:18
Thanks a lot for the detailed thread here and please excuse my slow response.<br><br>You've read the docs correctly on this, you will need to make sure that the integration if not maintained by the Langfuse team (in this case Diy) either adds model(name)+tokens OR total_cost when reporting llm calls as generations to langfuse. Happy to help figure this out with the dify team if you open an issue on their repo and reference it here.

**Comment by marcklingen** [comment] 2024-10-28 09:41
Did this work for you?

**Comment by luca1024-web** [comment] 2024-11-04 02:48
@LiHongYan666  Is the problem solved? I have the same problem.

**Comment by luca1024-web** [comment] 2024-11-04 03:09
> > Did this work for you?
> > @LiHongYan666 Is the problem solved? I have the same problem.
> > Yes. It'll be fine after the update.

langfuse:2.86.0

**Comment by luca1024-web** [comment] 2024-11-04 03:12
> > Did this work for you?
> > @LiHongYan666 Is the problem solved? I have the same problem.
> > Yes. It'll be fine after the update.
Langfuse:v2.86.0
Dify:0.10.2   
I'm using the latest version and still have this problem. It's basically the same as the problem you described, except that the cost can't be displayed. Can you help me?

**Comment by luca1024-web** [comment] 2024-11-04 03:52
@LiHongYan666 I suspect that my configuration is wrong. I don't know how to contact you, such as email, wx, penguin

**Comment by marcklingen** [comment] 2024-12-02 09:26
I'm unable to reproduce this. If I create a new model definition that matches the model name, then ingest traces, I see the cost applied correctly to the traces. Can you share a loom video of the problem?

**Comment by marcklingen** [comment] 2024-12-02 09:27
Closing this for now. Happy to reopen anytime when there are more details on how to reproduce

**Closed** 2024-12-02 09:27 UTC
Labels: 🐞❔ unconfirmed bug, integration-dify
