### ISSUE TITLE
bug: Duplicate event log to Langfuse trace when using openai wrapper and another native integration

### ISSUE THREAD

**Issue by michalwelna0** [langfuse/langfuse#1872] opened 2024-04-26 07:09 UTC
### Describe the bug

I wanted to use LlamaParse for parsing a set of documents (PDF/Doc/Docx) and index them to be able to ask custom questions to those documents. I performed a bunch of tests where I simply parse documents using LlamaParse and perform indexing step with LlamaIndex, I encountered duplication in token count (duplicated event log with LLM generation).

### To reproduce

```python

from llama_parse import LlamaParse
from langfuse.decorators import observe, langfuse_context
from llama_index.core import Settings, VectorStoreIndex
from llama_index.core.callbacks import CallbackManager
from llama_index.core.node_parser import MarkdownElementNodeParser
from llama_index.llms.openai import OpenAI
from llama_index.embeddings.openai import OpenAIEmbedding
from llama_index.core.postprocessor import SimilarityPostprocessor

import os
from langfuse import Langfuse
from pathlib import Path

os.environ["LANGFUSE_PUBLIC_KEY"] = ""
os.environ["LANGFUSE_SECRET_KEY"] = ""
os.environ["LANGFUSE_HOST"] = ""
os.environ["OPENAI_API_KEY"] = ""
os.environ["LLAMA_CLOUD_API_KEY"] = ""

langfuse = Langfuse()

folder_path = Path("path do local documents")
num_workers = len([path for path in folder_path .iterdir()])
parser = LlamaParse(
    result_type="markdown",
    verbose=True,
    language="en",
    num_workers=num_workers,  # should be number of documents, limit 10
)


@observe()
def index_docs(docs):
    Settings.llm = OpenAI(model="gpt-3.5-turbo")
    Settings.embed_model = OpenAIEmbedding(model="text-embedding-ada-002")
    node_parser = MarkdownElementNodeParser(
            llm=OpenAI(model="gpt-3.5-turbo"), num_workers=num_workers # should be number of documents, limit 10
        )
    langfuse_context.update_current_observation(name="Indexing documents")
    langfuse_callback_handler = langfuse_context.get_current_llama_index_handler()
    Settings.callback_manager = CallbackManager([langfuse_callback_handler])
 
    nodes = node_parser.get_nodes_from_documents(documents=docs)
    base_nodes, objects = node_parser.get_nodes_and_objects(nodes=nodes)
 
    index = VectorStoreIndex(nodes=base_nodes + objects)
 
    engine = index.as_query_engine(
        similarity_top_k=15,
        node_postprocessors=[
            SimilarityPostprocessor(similarity_cutoff=0.4)
        ],
        verbose=True,
    )
    return engine

def run():

    documents = parser.load_data([str(path) for path in folder_path.iterdir()])
    engine = index_docs(docs=documents)

run()
```

### Additional information

![Generations](https://github.com/langfuse/langfuse/assets/49715026/fb2d90a3-d56b-4258-afa9-f321929fe657)

Focus on red rectangles - marked duplicated events openai_llm and OpenAI-generation. This is problematic in terms of token usage estimation using Langfuse. From OpenAI side token usage is only logged once, so Langfuse is logging additional event with the same query and token usage.

![Trace view](https://github.com/langfuse/langfuse/assets/49715026/c6f5efc5-e4c1-432f-843f-11c3f6c5e78a)
Here is a screen shot from Langfuse UI with trace. As you can see `openai_llm` and `OpenAI-generation` event are duplicated.

**Comment by adamghowiba** [comment] 2024-04-27 03:49
I'm having the exact same issue where one is named OpenAI-Generation & the other is the named observation context

**Comment by marcklingen** [comment] 2024-04-30 13:03
Thanks for reporting this. Do you also use the openai sdk wrapper within your application? i.e. `from langfuse.openai import openai`

**Comment by marcklingen** [comment] 2024-04-30 22:21
Note: this might be addressed when switching to instrumentation: #1931 

> Thanks for reporting this. Do you also use the openai sdk wrapper within your application? i.e. from langfuse.openai import openai

This'd be super helpful to know here

**Comment by jtha** [comment] 2024-05-06 13:27
Hi @marcklingen, reporting in that I do see the same duplication of traces when using the observe decorator with the  openai sdk wrapper. Is this expected behaviour?

Anyhow, simple enough to use OpenAI's own sdk and setting up a function to log the token usage and cost.

**Comment by michalwelna0** [comment] 2024-05-06 13:37
Hi @marcklingen, thank you for your reply. To answer your question, yes I do use the SDK wrapper 
`from langfuse.openai import openai`

**Comment by leikoilja** [comment] 2024-10-02 15:26
i encountered the same now, @marcklingen, is is smth you guys are looking into?

**Comment by vivekmjude** [comment] 2024-10-03 11:57
Facing the same as well. I'm using `from langfuse.openai import openai` for OpenAI SDK in addition to LangChain in a nested trace. The duplicates show up within the parent trace at the end and outside all spans.
![image](https://github.com/user-attachments/assets/4b6c1d1d-a424-4aff-9a9f-6a900d8e8b92)

**Comment by marcklingen** [comment] 2024-10-04 05:26
Can you try whether importing the client as `from langfuse.openai import OpenAI` to explicitly use the Langfuse-wrapped OpenAI client solves the problem for you?

**Comment by leikoilja** [comment] 2024-10-04 05:35
@marcklingen , that's what I do, import the wrapper directly and using that. 2 traces are added for 1 transaction, one from langfuse wrapper correctly catching user/session ids and another trace for openai call with no extra info

**Comment by marcklingen** [comment] 2024-10-04 05:39
Can you share an example? do you import `openai` or `OpenAI`?

**Comment by leikoilja** [comment] 2024-10-04 06:28
> Can you share an example? do you import `openai` or `OpenAI`?

just double checked, sorry for the confusion, it's actually 
`from langchain_openai import ChatOpenAI` that i use with an attached 
`from langfuse.callback import CallbackHandler` callback handler 

```
            config = {
                "callbacks": [langfuse_handler],
            }
            response = client.invoke(prompt, config=config)
```

i can try to extract a minimum reproducible example later in the day if you wish :)

**Comment by marcklingen** [comment] 2024-10-04 06:38
That itself should be a non-issue, the question here is how you use the Langfuse openai integration (in case you use it at all). An example to reproduce this would be helpful

**Comment by leikoilja** [comment] 2024-10-06 13:01
> That itself should be a non-issue, the question here is how you use the Langfuse openai integration (in case you use it at all). An example to reproduce this would be helpful

I am so confused. No longer do i see double event logs per transaction. Couldn't replicate on the separate standalone project (with the latest version of langfuse & langchain) either. I will keep you updated if i notice the issue again and if i manage to replicate it. Thanks @marcklingen 💪

**Comment by marcklingen** [comment] 2024-10-07 09:38
Ok sounds great, seem like this was fixed in langchain. I’ll close this issue. Let me know if you can reproduce it, happy to reopen at any time.

**Closed by marcklingen** 2024-10-07 09:38 UTC
Labels: bug, sdk-python, integraton-llamaindex

**Comment by Canada-wet** [comment] 2024-11-29 16:19
Hit similar duplicated trace issue, which was due to using langchain callback handler while import langfuse openai integration at the same time (even without calling any langfuse openai module).

Removing all langfuse.openai imports resolved the issue.

thanks @marcklingen !

**Comment by marcklingen** [comment] 2024-11-29 17:58
> Hit similar duplicated trace issue, which was due to using langchain callback handler while import langfuse openai integration at the same time (even without calling any langfuse openai module).
> 
> Removing all langfuse.openai imports resolved the issue.
> 
> thanks @marcklingen !

thanks for sharing!

**Comment by Huarong** [comment] 2024-12-13 07:19
> Hit similar duplicated trace issue, which was due to using langchain callback handler while import langfuse openai integration at the same time (even without calling any langfuse openai module).
> 
> Removing all langfuse.openai imports resolved the issue.
> 
> thanks @marcklingen !

+1 for this.

**Comment by rishu931997** [comment] 2024-12-16 12:06
> Hit similar duplicated trace issue, which was due to using langchain callback handler while import langfuse openai integration at the same time (even without calling any langfuse openai module).
> 
> Removing all langfuse.openai imports resolved the issue.
> 
> thanks @marcklingen !

+1. Noticing same issue. Two traces with names: **OpenAI-generation** and **ChatOpenAI** are getting created with same content.Removing langfuse.openai imports removes duplicate trace.

**Comment by marcklingen** [comment] 2025-01-16 23:55
Can you remove the langfuse.openai import or do you use the integration at another point?

**Comment by yorickvP** [comment] 2025-01-17 14:44
I do use the integration at another point, so I'm not able to remove it. Sadly, this also means the cost estimates are off.

**Comment by ksundarraj-c-rpx** [comment] 2025-03-10 10:49
I am using litellm and sending the callbacks to langfuse, I am getting duplicate logs one named litellm generation and other named openai generation. How can I stop the openai generation also I am not using any wrapper of langfuse openai, 

here is my code:
`import litellm
from litellm import completion

from langfuse import Langfuse
from langfuse.decorators import observe, langfuse_context

litellm.success_callback = ["langfuse"]

response = completion(
        model=model_name,
        messages=messages,
        metadata={
          "session_id": f"session_{input_box}_{dt_object}"}
            )`

See below the screenshot of langfuse traces with duplicates 

![Image](https://github.com/user-attachments/assets/717c63d1-6861-442b-b752-c6cccb344890)

**Comment by marcklingen** [comment] 2025-03-10 15:09
@ksundarraj-c-rpx can you create a new bug report with this including all details necessary to reproduce this issue?

**Comment by ksundarraj-c-rpx** [comment] 2025-03-11 06:51
@marcklingen , found a fix with including
`openai.langfuse_enabled = False`

**Comment by marcklingen** [comment] 2025-03-12 08:48
Thanks for sharing! Does this result in openai calls still being captured within the trace?

**Comment by marcklingen** [comment] 2025-03-12 15:07
Ok makes sense as these are captured via litellm in this scenario. thanks for sharing!
